package com.tixue.dal.model;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_code
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_parent_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private Integer roleParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_note
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String roleNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.user_biz_type
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String userBizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.row_add_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private Date rowAddTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.row_update_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private Date rowUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_code
     *
     * @return the value of role.role_code
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_code
     *
     * @param roleCode the value for role.role_code
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_parent_id
     *
     * @return the value of role.role_parent_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public Integer getRoleParentId() {
        return roleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_parent_id
     *
     * @param roleParentId the value for role.role_parent_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setRoleParentId(Integer roleParentId) {
        this.roleParentId = roleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_note
     *
     * @return the value of role.role_note
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getRoleNote() {
        return roleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_note
     *
     * @param roleNote the value for role.role_note
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setRoleNote(String roleNote) {
        this.roleNote = roleNote == null ? null : roleNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.user_biz_type
     *
     * @return the value of role.user_biz_type
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getUserBizType() {
        return userBizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.user_biz_type
     *
     * @param userBizType the value for role.user_biz_type
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setUserBizType(String userBizType) {
        this.userBizType = userBizType == null ? null : userBizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.row_add_time
     *
     * @return the value of role.row_add_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.row_add_time
     *
     * @param rowAddTime the value for role.row_add_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.row_update_time
     *
     * @return the value of role.row_update_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.row_update_time
     *
     * @param rowUpdateTime the value for role.row_update_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", roleCode=").append(roleCode);
        sb.append(", roleName=").append(roleName);
        sb.append(", roleParentId=").append(roleParentId);
        sb.append(", roleNote=").append(roleNote);
        sb.append(", userBizType=").append(userBizType);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", rowUpdateTime=").append(rowUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}