package com.tixue.dal.model;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nick_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.real_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.log_password
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String logPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.pay_password
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String payPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.account_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.account_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mobile
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mobile_binding
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String mobileBinding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mail
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mail_binding
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String mailBinding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.type
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.state
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.real_name_authentication
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String realNameAuthentication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.pwd_error_count
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private Integer pwdErrorCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.change_lock_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private Date changeLockTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birthday
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_custom_type
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private String userCustomType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.row_add_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private Date rowAddTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.row_update_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private Date rowUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nick_name
     *
     * @return the value of user_info.nick_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nick_name
     *
     * @param nickName the value for user_info.nick_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.real_name
     *
     * @return the value of user_info.real_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.real_name
     *
     * @param realName the value for user_info.real_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.log_password
     *
     * @return the value of user_info.log_password
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getLogPassword() {
        return logPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.log_password
     *
     * @param logPassword the value for user_info.log_password
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setLogPassword(String logPassword) {
        this.logPassword = logPassword == null ? null : logPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.pay_password
     *
     * @return the value of user_info.pay_password
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.pay_password
     *
     * @param payPassword the value for user_info.pay_password
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.account_id
     *
     * @return the value of user_info.account_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.account_id
     *
     * @param accountId the value for user_info.account_id
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.account_name
     *
     * @return the value of user_info.account_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.account_name
     *
     * @param accountName the value for user_info.account_name
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mobile
     *
     * @return the value of user_info.mobile
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mobile
     *
     * @param mobile the value for user_info.mobile
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mobile_binding
     *
     * @return the value of user_info.mobile_binding
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getMobileBinding() {
        return mobileBinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mobile_binding
     *
     * @param mobileBinding the value for user_info.mobile_binding
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setMobileBinding(String mobileBinding) {
        this.mobileBinding = mobileBinding == null ? null : mobileBinding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mail
     *
     * @return the value of user_info.mail
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mail
     *
     * @param mail the value for user_info.mail
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mail_binding
     *
     * @return the value of user_info.mail_binding
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getMailBinding() {
        return mailBinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mail_binding
     *
     * @param mailBinding the value for user_info.mail_binding
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setMailBinding(String mailBinding) {
        this.mailBinding = mailBinding == null ? null : mailBinding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.type
     *
     * @return the value of user_info.type
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.type
     *
     * @param type the value for user_info.type
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.state
     *
     * @return the value of user_info.state
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.state
     *
     * @param state the value for user_info.state
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.real_name_authentication
     *
     * @return the value of user_info.real_name_authentication
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getRealNameAuthentication() {
        return realNameAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.real_name_authentication
     *
     * @param realNameAuthentication the value for user_info.real_name_authentication
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setRealNameAuthentication(String realNameAuthentication) {
        this.realNameAuthentication = realNameAuthentication == null ? null : realNameAuthentication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.pwd_error_count
     *
     * @return the value of user_info.pwd_error_count
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public Integer getPwdErrorCount() {
        return pwdErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.pwd_error_count
     *
     * @param pwdErrorCount the value for user_info.pwd_error_count
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setPwdErrorCount(Integer pwdErrorCount) {
        this.pwdErrorCount = pwdErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.change_lock_time
     *
     * @return the value of user_info.change_lock_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public Date getChangeLockTime() {
        return changeLockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.change_lock_time
     *
     * @param changeLockTime the value for user_info.change_lock_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setChangeLockTime(Date changeLockTime) {
        this.changeLockTime = changeLockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birthday
     *
     * @return the value of user_info.birthday
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birthday
     *
     * @param birthday the value for user_info.birthday
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_custom_type
     *
     * @return the value of user_info.user_custom_type
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public String getUserCustomType() {
        return userCustomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_custom_type
     *
     * @param userCustomType the value for user_info.user_custom_type
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setUserCustomType(String userCustomType) {
        this.userCustomType = userCustomType == null ? null : userCustomType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.row_add_time
     *
     * @return the value of user_info.row_add_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.row_add_time
     *
     * @param rowAddTime the value for user_info.row_add_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.row_update_time
     *
     * @return the value of user_info.row_update_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.row_update_time
     *
     * @param rowUpdateTime the value for user_info.row_update_time
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Jan 15 11:21:18 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", nickName=").append(nickName);
        sb.append(", realName=").append(realName);
        sb.append(", logPassword=").append(logPassword);
        sb.append(", payPassword=").append(payPassword);
        sb.append(", accountId=").append(accountId);
        sb.append(", accountName=").append(accountName);
        sb.append(", mobile=").append(mobile);
        sb.append(", mobileBinding=").append(mobileBinding);
        sb.append(", mail=").append(mail);
        sb.append(", mailBinding=").append(mailBinding);
        sb.append(", type=").append(type);
        sb.append(", state=").append(state);
        sb.append(", realNameAuthentication=").append(realNameAuthentication);
        sb.append(", pwdErrorCount=").append(pwdErrorCount);
        sb.append(", changeLockTime=").append(changeLockTime);
        sb.append(", birthday=").append(birthday);
        sb.append(", userCustomType=").append(userCustomType);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", rowUpdateTime=").append(rowUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}